### PR TITLE
Always use binary mode on std{in.out}

### PR DESCRIPTION
**Pull request by kkm000**

### CODE REVIEW

**Comment by kkm000** [comment]
@daanzu, PTAL. No other hacks required, as the library uses `ios:binary` whenever required. It's only the cin and cout that are affected.

**Comment by jtrmal** [comment]
LGTM

**Comment by daanzu** [comment]
@kkm000 I haven't tested it, but it looks good. I figured there should be a better place to put the modifications than where I did, but I didn't know my way around openfst enough to find it. Thanks for making the change!

**Comment by kkm000** [comment]
I did. I noticed that the extra 0x0A appears if you `fstcompile something
>temp.fst`, or pipe to xxd directly, but not when not using the redirect
`fstcompile something temp.fst`, letting  fstcompile open the file. You can
grep the source  `grep -w ::ios ` and then `-w ::ios::binary`: all binary
files are open with a correct flag. Only symbol files and remapping pairs
of integers from text files are opened without the binary flag.

Thanks for the code that changes the I/O type of an open file, as freopen
did not work: you cannot reassign stdin or stdout in Windows, those are
special, and defined as macros each calling a function.

 -kkm

**Pull request merged**
