### PR TITLE
Fix handling of newlines on stdout/stdin on windows (Fixes #20)

### LINKED ISSUE #20: stdout newline conversion of binary data
On Windows, outputting binary FST data to stdout from `fstcompile` (and I assume others) appears to perform newline conversion, inserting 0x0d before every 0x0a and rendering the data invalid. I've yet to look deeply into why. Do you know of a easy solution?

### PR DESCRIPTION
**Pull request by daanzu**
I am unsure of the best placement and style, so I am happy to modify to what you want. I certainly may not have covered all cases, but it's been working great for me for months. I haven't tested it on other OSs, though I don't see why it would cause problems.

### CODE REVIEW

**Comment by kkm000** [comment]
Ideally, this should go with the tools. The headers are used by Kaldi and other programs, I'd rather keep them as vanilla as possible.

**Comment by daanzu** [comment]
Hmm, it's been a while. I remember I initially started to implement it in the tools, but then I decided it should be moved to here, but I can't remember the details of my reasoning. Though, wouldn't any other user of the FST IO functions also want to output correct binary FST data, unmolested by windows new lines?

**Comment by kkm000** [comment]
This is an interesting question. Technically, the bug is in OpenFST: the standard requires using std::ios::binary flag on binary files. But there is a lot of software around that uses the library as part of Kaldi, which opens streams correctly. Let me see. I'm currently working on my Kaldi backlog. Next step is bringing up OpenFST up to date: there were incompatible interface changes that produce compile errors in Kaldi, and more stuff marked obsolete that I expect to be removed soon and cause even more problems. So I'd see syncing up to the upstream as a prerequisite to this work. Then we'll think. This is undeniably a bug, and better be fixed.

In Kaldi, all binaries, and only the binaries necessarily calls the argument parser, which would be a convenient common place to apply all binary-only stuff. In OpenFST, there is no such thing, but maybe some .h files may be hacked at a single point? I need to look. This FLAG_xxxx mechanism must have some common point where the flags are actually applied, so maybe we can make use of this less than perfect feature. It seems like it's there to stay, as there has been no change to it for nearly 7 years.

On a different topic, detecting the SDK version has also changed around the time VS16 came out. Previously, we need to know the exact third component of the version (10.0.12345) to be able to compile; MS fortunately fixed this inconvenience. But VS15 still needs to be supported.

**Comment by kkm000** [comment]
Blocked-By: #30

**Comment by daanzu** [comment]
Interesting. For now, for myself, it's not a big problem, as I have the patch applied to my fork to compile the FST binaries I need to work with streams/pipes on windows. Discovering the problem, however, was quite maddening. Test cases pretty much always worked fine; it usually required large graphs to have a high probability of encountering the problem (a new line conversion). At first, I just told myself I didn't really need to pipe compiled FSTs on windows; then eventually I buckled down and pulled out the hex editor. I should have guessed the problem earlier.

By the way, thanks for well-done and well-commented windows build setup here! It served as a great tutorial and reference to solving various issues I encountered while setting up my project's Continuous Integration.

**Comment by kkm000** [comment]
Closing in favor of #32, if you don't mind

**Pull request closed without merging**
