### PR TITLE
WIP: improving support for ZLIB and adding Python wrapper

### PR DESCRIPTION
**Pull request by jtrmal**
the python wrapper won't build under windows (cython generates code needing unistd.h and getpid())

### CODE REVIEW

**Comment by jtrmal** [comment]
I marked it as WIP, because I want to compile under Linux  (or mac), just to make sure the cmake config is compatible enough

**Comment by kkm000** [comment]
@jtrmal, sure, feel free to merge or ping me if you want me to review (but I can hardly be of much help with CMake scripts).

**Comment by kkm000** [comment]
@jtrmal, when you're back and have time, we should probably finish this?

**Comment by kkm000** [comment]
@jtrmal, do you want to keep this open? Anything changed with later versions? Looks like it's seriously out of date.

**Comment by jtrmal** [comment]
yeah, let me put it on my todo and try to finish it

**Pull request closed without merging**
