### PR TITLE
Fixed issue with attempt to install fstspecial-bin when HAVE_BIN=OFF.

### PR DESCRIPTION
**Pull request by alexismailov2**
I have added split install for fstspecial-bin and fstspecial for resolving this issue.

Signed-off-by: Alexander Ismailov <alexismailov2@gmail.com>

### CODE REVIEW

**Comment by jtrmal** [comment]
LGTM

**Comment by alexismailov2** [comment]
When it will be merged I will create a pull request to kaldi sources which use your fork.

**Comment by kkm000** [comment]
@alexismailov2, Thanks for the fix, and sorry for sitting on it, it fell off my radar.

@jtrmal, do feel free to merge when it looks good to you!

**Comment by jtrmal** [comment]
cannot merge :), not repo owner :)

**Comment by kkm000** [comment]
@jtrmal Aw shucks! Unable. Even tried [the REST API](https://docs.github.com/en/rest/collaborators/collaborators#add-a-repository-collaborator--parameters), but

> **`permissionstring`**
>
> The permission to grant the collaborator. **Only valid on organization-owned repositories.** 

Another reason to move this repo to the Kaldi org.

**Pull request merged**
