### PR TITLE
Fixes related to building on Windows with CMake, clang-cl, and HAVE_BIN=OFF

### LINKED ISSUE #35: Proposed fixes for building with CMake and Clang-cl on Windows with HAVE_BIN=OFF
Proposed fixes:

1. Disable intrinsic mapping when compiling with clang-cl.

openfst/src/include/fst/compat.h
```c++
#ifdef _MSC_VER
const char* basename(const char* path);
#ifndef __clang__
#include <intrin.h>
#define __builtin_popcount __popcnt

#ifdef _M_X64
// Using 64-bit MSVC intrinsics.
#define __builtin_popcountll __popcnt64
inline unsigned int __builtin_ctzll(std::uint64_t w) {
  unsigned long v;
  return _BitScanForward64(&v, std::uint32_t(w)) ? v : 0;
}
#else
// Using 32-bit MSVC intrinsics.
inline unsigned int __builtin_popcountll(std::uint64_t w) {
  return __popcnt(std::uint32_t(w)) + __popcnt(std::uint32_t(w >> 32));
}
inline unsigned int __builtin_ctzll(std::uint64_t w) {
  unsigned long v;
  return (_BitScanForward(&v, std::uint32_t(w)) ? v :
          _BitScanForward(&v, std::uint32_t(w >> 32)) ? v + 32 : 0);
}
#endif  // _M_X64
#endif  // __clang__
#endif  // _MSC_VER
```

2. Fix fstspecial-bin install logic

openfst/src/extensions/special/CMakeLists.txt
```cmake
set(FST_SPECIAL_INSTALL_TARGETS fstspecial)
if(HAVE_BIN)
  list(APPEND FST_SPECIAL_INSTALL_TARGETS fstspecial-bin)
endif()

install(TARGETS ${FST_SPECIAL_INSTALL_TARGETS}
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin
  ARCHIVE DESTINATION lib
)
```

3. Check for MSVC compiler instead of WIN32 OS

openfst/CMakeLists.txt
```cmake
if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  add_definitions(/bigobj)
  set(WHOLEFST "/WHOLEARCHIVE:fst")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${WHOLEFST}")
  #set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS 1)
  #this must be disabled unless the previous option (CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS) is enabled
  option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
else()
  option(BUILD_SHARED_LIBS "Build shared libraries" ON)
endif()
```

### PR DESCRIPTION
**Pull request by MantisClone**
See commit messages for details.
Fixes #35

### CODE REVIEW

**Comment by kkm000** [comment]
LGTM. @jtrmal, could you please have a look, too?

Tangentially, the problem with missing FST types without `whole-archive` exists in the original OpenFST, too. I was wondering how the heck it could work at all. Riddle solved, it simply does not. With OpenFST 1.7.9:
```
$ ./configure --disable-shared --enable-bin
$ make -j $(nproc)
$ cd 
$ echo "0" | src/bin/fstcompile >an.fst
$ src/bin/fstinfo an.fst
ERROR: GenericRegister::GetEntry: vector-fst.so: cannot open shared object file: No such file or directory
ERROR: MutableFst::Read: Unknown FST type "vector" (arc type = "standard"): an.fst
```
Whoops!

**Comment by jtrmal** [comment]
ack will do over the weekend
y.

**Comment by pengzhendong** [comment]
Any progress？

**Comment by kkm000** [comment]
@pengzhendong, very sorry, but both maintainers, I and @jtrmal, are at a final stage of quite a taxing work without a breather. 1-2 weeks.

**Comment by pengzhendong** [comment]
I'm sorry to bother you, any progress?

**Comment by MantisClone** [comment]
Any possibility we could merge or close this?

**Comment by jtrmal** [comment]
I'll put it on my todo.
y.

**Comment by MantisClone** [comment]
I just updated this PR to be in line with the `kkm000:winport` branch. I'm still hoping we can get it reviewed and merged at some point.

**Review by kkm000 — APPROVED** [review]

**Comment by kkm000** [comment]
@MantisClone, thank you for the patch, and apologies for sitting on your PR for a lifetime. Life happens...

**Pull request merged**
