### PR TITLE
Update CMakefiles for 1.7.3

### PR DESCRIPTION
**Pull request by kkm000**
* Add new _X_-main.cc files for executable sources _X_.cc
 * Bump SO version to 17
 * Set compile C++ standard to C++14 to compile ngram/ library.

List of added, deleted and renamed files is here: 9d503cd:
```
  R058  src/extensions/compress/compress-script.cc -> src/extensions/compress/compressscript.cc
  A     src/extensions/compress/fstcompress-main.cc
  D     src/extensions/compress/fstrandmod.cc
  A     src/extensions/far/farcompilestrings-main.cc
  A     src/extensions/far/farcreate-main.cc
  A     src/extensions/far/farequal-main.cc
  A     src/extensions/far/farextract-main.cc
  A     src/extensions/far/farinfo-main.cc
  A     src/extensions/far/farisomorphic-main.cc
  A     src/extensions/far/farprintstrings-main.cc
  A     src/extensions/linear/fstlinear-main.cc
  A     src/extensions/linear/fstloglinearapply-main.cc
  A     src/extensions/mpdt/mpdtcompose-main.cc
  A     src/extensions/mpdt/mpdtexpand-main.cc
  A     src/extensions/mpdt/mpdtinfo-main.cc
  A     src/extensions/mpdt/mpdtreverse-main.cc
  A     src/extensions/pdt/pdtcompose-main.cc
  A     src/extensions/pdt/pdtexpand-main.cc
  A     src/extensions/pdt/pdtinfo-main.cc
  A     src/extensions/pdt/pdtreplace-main.cc
  A     src/extensions/pdt/pdtreverse-main.cc
  A     src/extensions/pdt/pdtshortestpath-main.cc
  A     src/include/fst/expander-cache.h
  R027  src/include/fst/extensions/compress/compress-script.h -> src/include/fst/extensions/compress/compressscript.h
  D     src/include/fst/extensions/compress/randmod.h
  A     src/include/fst/power-weight-mappers.h
```
Built everything on Linux just fine, CMake 3.13.4

@jtrmal, could you PTAL? I'm planning to apply ports one version at a time, because it seems they are going with quite sweeping changes, using C++14 or 17 stuff. So far, 14 is enough.

### CODE REVIEW

**Comment by jtrmal** [comment]
Sorry, didn't notice, will deal with it tomorrow

**Comment by kkm000** [comment]
Sure, thanks! That's the largest one, all future cmake-related updates up
to the current 1.7.9 are insignificant if any at all.

**Review by jtrmal — APPROVED** [review]
LGTM. +tested on Mac and all good

**Comment by kkm000** [comment]
Super, thanks!

**Pull request merged**
